name       : heroku-cli
version    : 5.9.10
release    : 9
source     :
    - https://github.com/heroku/cli/archive/v5.9.10.tar.gz : 44796c7ef62ea572866e9fd14574b54a795c93b2b6b1b2e6cb01403ebd325e93
license    : MIT
networking : yes
component  : network.clients
summary    : The Heroku CLI is used to manage Heroku apps from the command line.
description: |
    The Heroku CLI is used to manage Heroku apps from the command line.
extract    : no
builddeps  :
    - git
    - golang
    - nodejs
rundeps    :
    - nodejs
setup      : |
    export GOPATH=$workdir
    export godir="src/github.com/heroku/cli"
    mkdir {bin,pkg,src}
    mkdir -p src/github.com/heroku/
    tar -xf $sources/v$version.tar.gz -C src/github.com/heroku/
    mv src/github.com/heroku/cli-$version $godir
    mv $godir/vendor/github.com/* src/github.com/
    mv $godir/vendor/golang.org src/
    cd $godir
    %patch -p1 < $pkgfiles/0001-Introduce-sane-install-recipe-for-Makefile.patch
build      : |
    export GOPATH=$workdir
    cd src/github.com/heroku/cli/
    %make build
install    : |
    cd src/github.com/heroku/cli/
    %make_install
